package com.laboratorio.java082;

import com.laboratorio.java082.cliente.Cliente;
import com.laboratorio.java082.cliente.Contacto;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

public class ClienteChat extends javax.swing.JFrame {

    /**
     * Creates new form ClienteChat
     */
    public ClienteChat() {
        initComponents();
        
        this.cliente = null;
        this.modelo = new DefaultListModel<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tNombre = new javax.swing.JTextField();
        bConectar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lParticipantes = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tEventos = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        tMensaje = new javax.swing.JTextField();
        bEnviar = new javax.swing.JButton();
        bCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Cliente del Chat");
        setResizable(false);

        jLabel1.setText("Nombre");

        tNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tNombreKeyReleased(evt);
            }
        });

        bConectar.setText("Conectar");
        bConectar.setEnabled(false);
        bConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConectarActionPerformed(evt);
            }
        });

        jLabel2.setText("Participantes");

        lParticipantes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lParticipantes.setEnabled(false);
        lParticipantes.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lParticipantesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lParticipantes);

        jLabel3.setText("Eventos");

        tEventos.setColumns(20);
        tEventos.setRows(5);
        tEventos.setEnabled(false);
        jScrollPane2.setViewportView(tEventos);

        jLabel4.setText("Mensaje");

        tMensaje.setEnabled(false);
        tMensaje.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tMensajeKeyReleased(evt);
            }
        });

        bEnviar.setText("Enviar");
        bEnviar.setEnabled(false);
        bEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEnviarActionPerformed(evt);
            }
        });

        bCerrar.setText("Cerrar");
        bCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tMensaje)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bEnviar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bConectar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(120, 120, 120)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(bCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bConectar))
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(bEnviar)
                    .addComponent(tMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bCerrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void agregarEvento(String mensaje) {
        String texto = tEventos.getText();
        texto += mensaje + '\n';
        tEventos.setText(texto);
    }
    
    public void actualizarLista() {
        List<Contacto> contactos = this.cliente.getContactos();
        
        modelo.clear();
        for (Contacto c : contactos) {
            modelo.addElement(c.getNombre());
        }
        lParticipantes.setModel(modelo);
    }
    
    public void mensajeError(String mensaje) {
        JOptionPane.showMessageDialog(null, mensaje,
                    "Error", JOptionPane.ERROR_MESSAGE);
    }
    
    public void cerrarVentana(int modo) {
        if (modo != 0) {
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error inesperado. Se cerrará la aplicación.",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
        System.exit(modo);
    }
    
    private void bCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCerrarActionPerformed
        if (this.cliente != null) {
            cliente.desconectar();
        }
        
        System.exit(0);
    }//GEN-LAST:event_bCerrarActionPerformed

    private void tNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tNombreKeyReleased
        if (tNombre.getText().length() > 2) {
            bConectar.setEnabled(true);
        } else {
            bConectar.setEnabled(false);
        }
    }//GEN-LAST:event_tNombreKeyReleased

    private void bConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConectarActionPerformed
        tNombre.setEditable(false);
        bConectar.setEnabled(false);
        // Activar los demás.
        
        try {
            cliente = new Cliente(this, "127.0.0.1", 2468, tNombre.getText());
            cliente.start();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error al establecer la conexión con el servidor",
                    "Error", JOptionPane.ERROR_MESSAGE);
            System.exit(1);
            return;
        }
        
        agregarEvento("Se ha establecido la conexión");
        lParticipantes.setEnabled(true);
    }//GEN-LAST:event_bConectarActionPerformed

    private void lParticipantesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lParticipantesValueChanged
        int sel = lParticipantes.getSelectedIndex();
        
        if (sel == -1) {
            tMensaje.setEnabled(false);
        } else {
            tMensaje.setEnabled(true);
        }
    }//GEN-LAST:event_lParticipantesValueChanged

    private void tMensajeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tMensajeKeyReleased
        String str = tMensaje.getText().trim();
        if (str.length() > 0) {
            bEnviar.setEnabled(true);
        } else {
            bEnviar.setEnabled(false);
        }
    }//GEN-LAST:event_tMensajeKeyReleased

    private void bEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEnviarActionPerformed
        int sel = lParticipantes.getSelectedIndex();
        if (sel == -1) {
            return;
        }
        
        String str = tMensaje.getText().trim();
        if (str.length() == 0) {
            return;
        }
        
        cliente.enviarMensaje(sel, str);
        tMensaje.setText("");
        bEnviar.setEnabled(false);
    }//GEN-LAST:event_bEnviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteChat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCerrar;
    private javax.swing.JButton bConectar;
    private javax.swing.JButton bEnviar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lParticipantes;
    private javax.swing.JTextArea tEventos;
    private javax.swing.JTextField tMensaje;
    private javax.swing.JTextField tNombre;
    // End of variables declaration//GEN-END:variables

    private Cliente cliente;
    private DefaultListModel<String> modelo;
}